/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 82cb4932fc8a8e2716c8cc6b10a4d546)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_API_TOKEN: string;
		EMBEDDING_MODEL: string;
		EMBEDDING_VECTOR_DIMENSIONS: string;
		TEXT_MODEL: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		DB: D1Database;
		VECTORIZE_INDEX: VectorizeIndex;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN" | "EMBEDDING_MODEL" | "EMBEDDING_VECTOR_DIMENSIONS" | "TEXT_MODEL">> {}
}
